exclude: migrations
default_stages: [commit]
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-ast
    - id: end-of-file-fixer
    - id: double-quote-string-fixer


- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
      args: [--config=backend/pyproject.toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --ignore-missing-imports]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.281
  hooks:
    - id: ruff
      args: [--fix, --exit-zero]

default_language_version:
  python: python3.11
