# Generated by Django 5.0 on 2023-12-23 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='providers',
            new_name='employer',
        ),
    ]
