# Generated by Django 5.0 on 2023-12-24 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_rename_providers_user_employer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
