# Generated by Django 5.0 on 2023-12-21 08:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=32)),
                (
                    'provider',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='supplier',
                        to='provider.provider',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
