# Generated by Django 5.0 on 2023-12-25 08:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('first_date_of_release', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductToProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='provider.product'
                    ),
                ),
            ],
            options={
                'db_table': 'products_to_providers',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=32)),
                (
                    'level',
                    models.IntegerField(
                        choices=[
                            (0, 'First Level'),
                            (1, 'Second Level'),
                            (2, 'Third Level'),
                            (3, 'Fourth Level'),
                            (4, 'Fifth Level'),
                        ]
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customers',
                        to='provider.provider',
                    ),
                ),
                (
                    'retail_products',
                    models.ManyToManyField(through='provider.ProductToProvider', to='provider.product'),
                ),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.AddField(
            model_name='producttoprovider',
            name='provider',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='products', to='provider.provider'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='product_for',
            field=models.ManyToManyField(through='provider.ProductToProvider', to='provider.provider'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('house_no', models.CharField(max_length=150)),
                (
                    'provider',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='provider.provider',
                    ),
                ),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='producttoprovider',
            unique_together={('product', 'provider')},
        ),
    ]
