# Generated by Django 5.0 on 2023-12-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='type',
            field=models.CharField(
                choices=[
                    ('FACTORY', 'Factory'),
                    ('DISTRIBUTOR', 'Distributor'),
                    ('DEALERSHIP', 'Dealership'),
                    ('LARGE_RETAIL', 'Large Retail'),
                    ('INDIVIDUAL_ENTREPRENEUR', 'Individual Entrepreneur'),
                ],
                default='FACTORY',
                max_length=35,
            ),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('house_no', models.CharField(max_length=150)),
                (
                    'providers',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='provider.provider',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('first_date_of_release', models.DateField(blank=True, null=True)),
                (
                    'providers',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to='provider.provider',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
