# Generated by Django 5.0 on 2023-12-23 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('provider', '0002_provider_level_alter_provider_provider_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='providers',
            new_name='provider',
        ),
    ]
