# Generated by Django 5.0 on 2023-12-23 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('provider', '0003_rename_providers_contact_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='providers',
            new_name='provider',
        ),
    ]
