# Generated by Django 5.0 on 2023-12-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('provider', '0004_rename_providers_product_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='provider',
            table='providers',
        ),
        migrations.CreateModel(
            name='ProductToProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='provider.product'
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='products', to='provider.provider'
                    ),
                ),
            ],
            options={
                'db_table': 'products_to_providers',
                'unique_together': {('provider', 'product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_for',
            field=models.ManyToManyField(through='provider.ProductToProvider', to='provider.provider'),
        ),
    ]
